### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by ennynz** [ennynz/kickarts-refresh#1]
work out the mobile view

**Comment by ennynz** [comment]
most of all mobile media queries have been set up. just waiting for completition of project for final check.

**Comment by jaeming** [comment]
I've gone back over most of these mobile views and fixed a bunch of stuff. there is some small problem with search section on the ios simulator where opening the date selection zooms in slightly to the screen and causes some formatting problem with the menu and makes a part of the page off-screen.  I've made some adjustments here but need to do more debugging to fix it.

**Comment by jaeming** [comment]
also just realised the audio player (that doesn't have styling yet) isn't exactly responsive. A smaller timeline will help but will wait till it's styled to make these adjustments most likely.

**Comment by ennynz** [comment]
all done.
